The ROCm CSB was broken by the following commit :
https://github.com/tensorflow/tensorflow/commit/880cad85987e8948774f9bae24b1420074534f00

The commit leads to linker errors like below :

```
bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/serialize_sparse_op/serialize_sparse_op.o:
serialize_sparse_op.cc:function tensorflow::(anonymous namespace)::SerializeManySparseOp<tensorflow::tstring, tensorflow::Variant>::Compute(tensorflow::OpKernelContext*): error:
undefined reference to 'tensorflow::DataTypeToEnum<tensorflow::tstring>::value'
```

The breakage seems to be something that should affect all platforms (not just ROCm)

The cause of the error is that the static member varibale `DataTypeToEnum<T>::value` is declared,
but not defined in the file `tensorflow/core/framework/types.h` file. Therefore any use of it
as a "reference" will lead to linker errors. The commit above seems to introduce two such uses.

This commit fixes the issue by adding the explicit definition of `DataTypeToEnum<T>::value` in `types.cc` file