Do not crash if Model.summary called on subclassed model with unused layer.
Fixes https://github.com/tensorflow/tensorflow/issues/36198. Before, the error was in the form:

  ValueError: You tried to call `count_params` on concatenate, but the layer isn't built. You can build it manually via: `concatenate.build(batch_input_shape)`.

PiperOrigin-RevId: 345486596
Change-Id: I334994d3b31e53af40be7c33261f4e3af5d799b2