Fix int32-overflow error in shape computation.
I got the following error message before tracking down this bug:
InvalidArgumentError: Input to reshape is a tensor with 2764800000 values, but the requested shape requires a multiple of 2764800
Change: 114562418