Fix Huber Loss crashes due to data type mismatch
This PR tries to address the issue raised in 39004 where
setting keras backend to 'float64' causes Huber Loss crash:
```
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/losses.py:1440 huber
        math_ops.multiply(delta, linear)),
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:490 multiply
        return gen_math_ops.mul(x, y, name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py:6153 mul
        "Mul", x=x, y=y, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:506 _apply_op_helper
        inferred_from[input_arg.type_attr]))

    TypeError: Input 'y' of 'Mul' Op has type float64 that does not match type float32 of argument 'x'.

```

This PR fixes the crash by casting delta the same way as y_pred and y_true accordingly.

This PR fixes 39004

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>