Fix build failure with CUDA 11.0.0.
A symbol was used that was only included starting in CUDA 11.1.0. The error was:

    error: 'CUDA_ARRAY_SPARSE_PROPERTIES' was not declared in this scope

PiperOrigin-RevId: 372459250
Change-Id: I7a4b380129e0aa4c4a6bc19d517c79d98e342443