[MHLO] Add explicit dependencies on MLIRIR
These include headers from MLIRIR depends on generated files, so without the dependency edge, even the header includes can fail:

```
mlir/include/mlir/IR/Location.h:108:10: fatal error: 'mlir/IR/BuiltinLocationAttributes.h.inc' file not found
#include "mlir/IR/BuiltinLocationAttributes.h.inc"
```

Current errors reproducible with:

- `ninja clean && ninja -j 1 MhloInferShapeEqualityOpInterface`
- `ninja clean && ninja -j 1 LmhloStructuredInterface`

PiperOrigin-RevId: 407398695
Change-Id: I998a5372579e28e141b148e9496ce96619cfed19