Roll back #37719
Breaks on MacOS:

```
ERROR: /Volumes/BuildData/tmpfs/tensor_flow/tensorflow/cc/BUILD:507:1: Couldn't build file tensorflow/cc/ops/array_ops_gen_cc: Linking of rule '//tensorflow/cc:ops/array_ops_gen_cc' failed (Exit 1)
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
PiperOrigin-RevId: 301890882
Change-Id: I3b98bf8bae271567fa31fccce15269460ef52c81