[oneDNN aarch64] Remove a misplaced mutex guard hint.
Fix the following build error:
```
./tensorflow/core/util/mkl_util.h:1981:19: error: use of undeclared identifier 'lru_mu_'
    TF_GUARDED_BY(lru_mu_)
                  ^
1 error generated.
```

`lru_mu_` is defined in `LRUCache` to guard member variables in there, so it shouldn't be here (`lru_mu_` is not defined here, and the guard hint isn't accurate).

PiperOrigin-RevId: 496716019