TFLite: tools: make: add fftsg2d.c file in the build resources for libtensorflow-lite.a
lite/kernels/rfft2d.cc has reference to rdft2d.
As a consequence, libtensorflow-lite.a need to include fft2d/fftsg2d.c source
in its build.

If fftsg2d.c is not part of libtensorflow-lite.a, a C/C++ application
that use the libtensorflow-lite.a static library is not able to link
with the following error:
rfft2d.cc:(.text+0x594): undefined reference to `rdft2d'

Signed-off-by: Vincent ABRIOU <vincent.abriou@st.com>