Fix EarlyStopping callback when no progress is ever made.
The error was:
File "tensorflow/python/keras/callbacks.py", line 1782, in on_epoch_end
    self.model.set_weights(self.best_weights)
File "tensorflow/python/keras/engine/base_layer.py", line 1850, in set_weights
    if expected_num_weights != len(weights):
TypeError: object of type 'NoneType' has no len()

We can't put the initialization inside "on_begin" functions because not all weights are initialized.

PiperOrigin-RevId: 351416566
Change-Id: I800eb91f37afd25ec3272b9405415d42375f3204