Use V2 summary writer creation logic in Keras callback
A single `TensorBoard` Keras callback instance can now be used in
multiple calls to `fit` or `evaluate`. Prior to this change, the
underlying writer resource would be freed after the first call, causing
the second call to fail. The bulk of the heavy lifting was done in
cl/235249883; this change just hooks up the callback to the new
interface.

Fixes <#25707>.

Tested:
Regression test added; prior to this change, it fails with:

```
NotFoundError: Resource localhost/logdir:/<snip>/N10tensorflow22SummaryWriterInterfaceE does not exist. [Op:WriteGraphSummary]
```
PiperOrigin-RevId: 236047085