[OpenMP] Fix undeclared identifier in eigen_support.cc
When OpenMP is enabled, the following error occurs during a
compilation of the `tensorflow/lite/kernels/eigen_support.cc` unit:

tensorflow/lite/kernels/eigen_support.cc:42:23: error: use of undeclared
identifier 'context'
  Eigen::setNbThreads(context->recommended_num_threads);

The `SetEigenNbThreads` method already gets the number of threads as the
`threads` parameter and doesn't need to calculate it using a method of
the `context` variable, so the invocation of the `Eigen::setNbThreads`
member must be changed a little bit.

Signed-off-by: Pavel Samolysov <samolisov@gmail.com>