Fix float64 BatchNormalization.
It used to raise the error:
    TypeError: Value passed to parameter 'x' has DataType float64 not in list of allowed values: float16, bfloat16, float32

This is done by not using the fused implementation when float64 is used. We should later add support to float64 for the fused implementation.

Fixes https://github.com/tensorflow/tensorflow/issues/33365

PiperOrigin-RevId: 300166944
Change-Id: I9d061f92a656f7e2a9645e911a32e7e451199024