[ROCm] Fix for ROCm CSB Breakage - 201022
The following commit introduces a failure on in the `//tensorflow/python/kernel_tests:linalg_grad_test_gpu` test on the ROCm Platform

https://github.com/tensorflow/tensorflow/commit/3ce466a482f3ef247882e069e810d79913cfe940

The failure is in the `MatrixExponentialGradient` subtest, and the errors we get are of the following form

```
======================================================================
ERROR: test_MatrixExponentialGradient_float64_5_5 (__main__.MatrixUnaryFunctorGradientTest)
test_MatrixExponentialGradient_float64_5_5 (__main__.MatrixUnaryFunctorGradientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/linalg_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: No registered 'MatrixSolve' OpKernel for 'GPU' devices compatible with node {{node MatrixSolve}}
	.  Registered:  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_HALF]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]

	 [[MatrixSolve]]
	 [[matrix_exponential_1/cond/PartitionedCall/matrix_exponential_1/cond]]
	 [[PartitionedCall/gradients/matrix_exponential_1/cond_grad/StatelessIf/then/_22/gradients/Neg_grad/Neg/_73]]
  (1) Not found: No registered 'MatrixSolve' OpKernel for 'GPU' devices compatible with node {{node MatrixSolve}}
	.  Registered:  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_HALF]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]

	 [[MatrixSolve]]
	 [[matrix_exponential_1/cond/PartitionedCall/matrix_exponential_1/cond]]
0 successful operations.
0 derived errors ignored.

```

The regression was fixed by the subsequent commit, https://github.com/tensorflow/tensorflow/commit/7d57263720c7d2c88861f2f325e8ca1bd02deb38

and then re-introduced when parts of the above commits were rolled back by the following commit

https://github.com/tensorflow/tensorflow/commit/fb22dff31744a9fdc571f6c2bf8743eb2844eb95

The regression seems to occur on the ROCm platform because the "MatrixSolve" operator is currently only enabled for the CUDA platform for GPUs, and not on the ROCm platform.

This commit is to temporarily disable the subtest on the ROCm platform, to get the ROCm CSB to pass. It can be reverted once the reverted changes are put back in.