Avoid using init-statements in if
Otherwise,

    error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'

will be triggered when building jaxlib with MSVC