#tf-data Fix memory_cleanup_test
Previously the test was failing in TF 2.12 with

    o for o in gc.get_objects() if isinstance(o, internal.NativeObject)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists

Now we will check whether `o` is a weakref proxy object before calling `isinstance` with it.

PiperOrigin-RevId: 508103963